Channels threads
wilmhit/Meduza pull request #5
Opened 2021-05-08 17:37 UTC by lewy12121212

Dodano klasę "single_channel" w celu obsługi pojedynczego kanału. 
Dodano mechanizm tworzenia i usuwania wątku kanału w zależności od obecności użytkownika.

2021-05-08 17:47 UTC, wilmhit requested changes

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
>              0:{
dict z indeksami int -> lista

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
> +            channnel_port = self.get_port_num()
czemu tak? Nie lepiej w dict to wywołać?

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
> +            self.channels[channel_number]['thread'].setUp_start_stop_value(True)
camelCase mieszany z snake_case?

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
> +            self.channels[channel_number]['thread'].setUp_start_stop_value(True)
Czemu ta funkjcja przyjmuje True na sztywno?

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
> +
EOF

2021-05-08 17:47 UTC, wilmhit commented on server/channels.py
> +            self.channels[channel_number]['thread'].setUp_start_stop_value(False)
Jak masz na sztywno podawać zawsze True/False to zrób 2 oddzielne metody

2021-05-08 17:47 UTC, wilmhit commented on server/single_channel.py
> +    def setUp_start_stop_value(self, empty):
Zwsze - Jak twoja funckja ma mieć `if` na całą funkcje to zrób z tego dwie

2021-05-08 17:47 UTC, wilmhit commented on server/single_channel.py
> +            print("i'm a thread! :) nubmer: ", self.number_of_channel)
Literówka

2021-05-08 17:47 UTC, wilmhit commented on server/voip_server.py
> +        self.client_manager.listen()
EOF

2021-05-10 17:11 UTC, lewy12121212 commented on server/channels.py
> +            channnel_port = self.get_port_num()
zdecydowanie lepiej :) - zostało po poprzednich próbach i zapomniałem zmienić.

2021-05-10 17:15 UTC, lewy12121212 commented on server/channels.py
>              0:{
nie kumam jak ma to wyglądać :/
help me pls

2021-05-10 17:16 UTC, lewy12121212 commented on server/channels.py
> +
?

2021-05-11 07:06 UTC, wilmhit commented on server/channels.py
> +            self.channels[channel_number]['thread'].setUp_start_stop_value(True)
Powinno. `setUp_start_stop_value` to metoda.

2021-05-11 07:07 UTC, wilmhit commented on server/channels.py
> +
Na końcu pliku zawsze pusta linikja powinna być

2021-05-11 07:12 UTC, wilmhit commented on server/single_channel.py
> +    def setUp_start_stop_value(self, empty):
W tym przypadku może być:
```
self._running = empty
```

2021-05-15 19:15 UTC, wilmhit approved these changes

2021-05-16 09:22 UTC, merged